name: myapp
description: "Mensagens biblicas"
publish_to: 'none' 

version: 2.3.0+17

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  path_provider: ^2.1.3
  dio: ^5.5.0+1
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  file_picker: ^9.1.0
  google_mobile_ads: ^5.1.0
  shimmer: ^3.0.0
  transparent_image: ^2.0.1
  firebase_messaging: ^15.1.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo2.png
    - images/logobg.png
    - images/background.jpeg
    - images/logoapp.png
    - images/too.png


flutter_launcher_icons:
  android: true
  image_path: "images/logoapp.png"
